# Generated by Django 6.0.3 on 2026-04-06 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('name_uz', models.CharField(blank=True, max_length=255, verbose_name='Название (uz)')),
                ('former_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Прежнее название (ru)')),
                ('former_name_uz', models.CharField(blank=True, max_length=255, verbose_name='Прежнее название (uz)')),
                ('current_purpose_ru', models.CharField(blank=True, max_length=255, verbose_name='Назначение сейчас (ru)')),
                ('current_purpose_uz', models.CharField(blank=True, max_length=255, verbose_name='Назначение сейчас (uz)')),
                ('historical_purpose_ru', models.CharField(blank=True, max_length=255, verbose_name='Назначение ранее (ru)')),
                ('historical_purpose_uz', models.CharField(blank=True, max_length=255, verbose_name='Назначение ранее (uz)')),
                ('address_ru', models.TextField(blank=True, verbose_name='Адрес (ru)')),
                ('address_uz', models.TextField(blank=True, verbose_name='Адрес (uz)')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('year_range', models.CharField(blank=True, max_length=50, verbose_name='Диапазон лет (строка)')),
                ('architectural_style_ru', models.CharField(blank=True, max_length=255, verbose_name='Стиль (ru)')),
                ('architectural_style_uz', models.CharField(blank=True, max_length=255, verbose_name='Стиль (uz)')),
                ('architect_ru', models.CharField(blank=True, max_length=255, verbose_name='Архитектор (ru)')),
                ('architect_uz', models.CharField(blank=True, max_length=255, verbose_name='Архитектор (uz)')),
                ('architectural_description_ru', models.TextField(blank=True, verbose_name='Архитектурное описание (ru)')),
                ('architectural_description_uz', models.TextField(blank=True, verbose_name='Архитектурное описание (uz)')),
                ('history_ru', models.TextField(blank=True, verbose_name='История (ru)')),
                ('history_uz', models.TextField(blank=True, verbose_name='История (uz)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Краткое описание (ru)')),
                ('short_description_uz', models.TextField(blank=True, verbose_name='Краткое описание (uz)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в каталоге')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект наследия',
                'verbose_name_plural': 'Объекты наследия',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('before_image', models.ImageField(upload_to='before_after/')),
                ('after_image', models.ImageField(upload_to='before_after/')),
                ('year_before', models.IntegerField(blank=True, null=True)),
                ('year_after', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_pairs', to='heritage.heritageobject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AudioGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intro', 'Краткий экскурс'), ('atmosphere', 'Атмосферный звук'), ('historian', 'Голос историка')], max_length=20)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('transcript_ru', models.TextField(blank=True, verbose_name='Расшифровка (ru)')),
                ('transcript_uz', models.TextField(blank=True, verbose_name='Расшифровка (uz)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_guides', to='heritage.heritageobject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='architecture_details/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_details', to='heritage.heritageobject')),
            ],
            options={
                'verbose_name': 'Архитектурная деталь',
                'verbose_name_plural': 'Архитектурные детали',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('role_ru', models.CharField(blank=True, max_length=255)),
                ('role_uz', models.CharField(blank=True, max_length=255)),
                ('bio_ru', models.TextField(blank=True)),
                ('bio_uz', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='figures/')),
                ('is_architect_bio', models.BooleanField(default=False, verbose_name='Это биография архитектора')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_figures', to='heritage.heritageobject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
