# Generated by Django 6.0.3 on 2026-06-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_0005_squashed'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beforeafterpair',
            name='after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_pairs', to='media_files.mediafile', verbose_name="Фото 'Стало'"),
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='before',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_pairs', to='media_files.mediafile', verbose_name="Фото 'Было'"),
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='heritage_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beforeAfterPairs', to='heritage.heritageobject', verbose_name='Объект наследия'),
        ),
    ]
