# Generated by Django 6.0.3 on 2026-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageobject',
            name='cover_image',
            field=models.URLField(blank=True, default='', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
