# Generated by Django 6.0.5 on 2026-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_alter_heritageobject_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturedetail',
            name='image',
            field=models.URLField(blank=True, default='', verbose_name='Изображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='after_image',
            field=models.URLField(blank=True, verbose_name='Изображения после'),
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='before_image',
            field=models.URLField(blank=True, verbose_name='Изображения до'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='photo',
            field=models.URLField(blank=True, default='', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
