# Generated by Django 6.0.3 on 2026-06-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_alter_beforeafterpair_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('ping_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DB heartbeat',
                'verbose_name_plural': 'DB heartbeats',
            },
        ),
    ]
