# Generated by Django 6.0.3 on 2026-05-17 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_alter_architecturedetail_image_and_more'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event_ru', models.CharField(max_length=500)),
                ('event_uz', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeritageListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('yearRange', models.CharField(blank=True, max_length=50)),
                ('address_ru', models.CharField(blank=True, max_length=255)),
                ('address_uz', models.CharField(blank=True, max_length=255)),
                ('coverImageUrl', models.URLField(blank=True)),
                ('shortDescription_ru', models.CharField(blank=True, max_length=255)),
                ('shortDescription_uz', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isPublished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='architecturedetail',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='beforeafterpair',
            options={'ordering': ['sort_order'], 'verbose_name': 'Пара Было/Стало', 'verbose_name_plural': 'Пары Было/Стало'},
        ),
        migrations.AlterModelOptions(
            name='heritageobject',
            options={'ordering': ['order', 'name_ru']},
        ),
        migrations.RemoveField(
            model_name='architecturedetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='heritage',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='order',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='beforeafterpair',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='architectural_description_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='architectural_description_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='architectural_style_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='architectural_style_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='current_purpose_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='current_purpose_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='former_name_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='former_name_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='historical_purpose_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='historical_purpose_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='year_built',
        ),
        migrations.RemoveField(
            model_name='heritageobject',
            name='year_range',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='is_architect_bio',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='photo',
        ),
        migrations.AddField(
            model_name='architecturedetail',
            name='imageCredit_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='architecturedetail',
            name='imageCredit_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='architecturedetail',
            name='imageSourceUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='architecturedetail',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='after',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='after_pairs', to='media_files.mediafile', verbose_name="Фото 'Стало'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='before',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='before_pairs', to='media_files.mediafile', verbose_name="Фото 'Было'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (UZ)'),
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='heritage_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beforeAfterPairs', to='heritage.heritageobject', verbose_name='Объект наследия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='label_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название пары (RU)'),
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='label_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название пары (UZ)'),
        ),
        migrations.AddField(
            model_name='beforeafterpair',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='architecturalDescription_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='architecturalDescription_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='architecturalStyle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='architecturalStyle_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='coverImageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='currentPurpose_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='currentPurpose_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='formerName_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='formerName_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='historicalPurpose_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='historicalPurpose_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='mapUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='shortDescription_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='shortDescription_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='tourEntryUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='tourPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='visualStyleNotes_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='visualStyleNotes_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='yearBuilt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='yearBuiltLabel_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='yearBuiltLabel_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='yearRange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='bioSourceCredit_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='bioSourceCredit_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='bioSourceUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='photoUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='heritage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectureDetails', to='heritage.heritageobject'),
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='year_after',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Год 'Стало'"),
        ),
        migrations.AlterField(
            model_name='beforeafterpair',
            name='year_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Год 'Было'"),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='address_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='address_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='architect_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='architect_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='history_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='history_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='heritage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicalFigures', to='heritage.heritageobject'),
        ),
        migrations.CreateModel(
            name='AudioGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narratorLabel_ru', models.CharField(blank=True, max_length=255)),
                ('narratorLabel_uz', models.CharField(blank=True, max_length=255)),
                ('transcript_ru', models.TextField(blank=True)),
                ('transcript_uz', models.TextField(blank=True)),
                ('atmosphereDescription_ru', models.TextField(blank=True)),
                ('atmosphereDescription_uz', models.TextField(blank=True)),
                ('musicSuggestion_ru', models.TextField(blank=True)),
                ('musicSuggestion_uz', models.TextField(blank=True)),
                ('heritage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audioGuide', to='heritage.heritageobject')),
            ],
        ),
        migrations.CreateModel(
            name='AudioGuideTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('shortTitle_ru', models.CharField(blank=True, max_length=255)),
                ('shortTitle_uz', models.CharField(blank=True, max_length=255)),
                ('fullTitle_ru', models.CharField(blank=True, max_length=255)),
                ('fullTitle_uz', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='heritage.audioguide')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('role_ru', models.CharField(blank=True, max_length=255)),
                ('role_uz', models.CharField(blank=True, max_length=255)),
                ('bio_ru', models.TextField(blank=True)),
                ('bio_uz', models.TextField(blank=True)),
                ('photoUrl', models.URLField(blank=True)),
                ('heritage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architectBio', to='heritage.heritageobject')),
                ('milestones', models.ManyToManyField(blank=True, to='heritage.biographymilestone')),
            ],
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='milestones',
            field=models.ManyToManyField(blank=True, to='heritage.biographymilestone'),
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption_ru', models.CharField(blank=True, max_length=255)),
                ('caption_uz', models.CharField(blank=True, max_length=255)),
                ('isHistorical', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True)),
                ('sourceUrl', models.URLField(blank=True)),
                ('credit_ru', models.CharField(blank=True, max_length=255)),
                ('credit_uz', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='heritage.heritageobject')),
                ('heritage_history_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historyMedia', to='heritage.heritageobject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='AudioGuideItem',
        ),
    ]
