# Generated by Django 6.0.3 on 2026-06-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_dbheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectbio',
            name='photoUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageSourceUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='audioguidetrack',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='heritagelistitem',
            name='coverImageUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='coverImageUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='mapUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='tourEntryUrl',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='bioSourceUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='photoUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='sourceUrl',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
