# Generated by Django 6.0.3 on 2026-06-06 01:34

import heritage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0004_expand_url_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectbio',
            name='photoUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageSourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='audioguidetrack',
            name='url',
            field=heritage.fields.FlexibleUrlField(validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritagelistitem',
            name='coverImageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='coverImageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='mapUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='tourEntryUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, null=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='bioSourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='photoUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='sourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='url',
            field=heritage.fields.FlexibleUrlField(validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
    ]
