# Generated by Django 6.0.3 on 2026-06-06 01:54

import heritage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0005_flexible_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobject',
            name='tourGoogleDriveFileId',
            field=models.CharField(blank=True, help_text='ID файла zip на Google Drive или полная share-ссылка.', max_length=128),
        ),
        migrations.AddField(
            model_name='heritageobject',
            name='tourPackUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='architectbio',
            name='photoUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageSourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='architecturedetail',
            name='imageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='audioguidetrack',
            name='url',
            field=heritage.fields.FlexibleUrlField(validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritagelistitem',
            name='coverImageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='coverImageUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='mapUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='heritageobject',
            name='tourEntryUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, help_text='Опционально. Если пусто — на фронте подставится /tour-packs/{slug}/index.htm.', null=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='bioSourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='photoUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='sourceUrl',
            field=heritage.fields.FlexibleUrlField(blank=True, validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='url',
            field=heritage.fields.FlexibleUrlField(validators=[heritage.fields.validate_flexible_url, heritage.fields.validate_flexible_url]),
        ),
    ]
