# Generated by Django 6.0.3 on 2026-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_uz', models.CharField(blank=True, max_length=255, verbose_name='Название (UZ)')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио')], max_length=10, verbose_name='Тип медиа')),
                ('alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt (RU)')),
                ('alt_uz', models.CharField(blank=True, max_length=255, verbose_name='Alt (UZ)')),
                ('caption_ru', models.TextField(blank=True, verbose_name='Подпись (RU)')),
                ('caption_uz', models.TextField(blank=True, verbose_name='Подпись (UZ)')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='Источник')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
