# Generated by Django 6.0.3 on 2026-06-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_expand_url_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
